/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "transfer.h"


void
transfer_1(char *host, char *filename, char filecontent)
{
	CLIENT *clnt;
	int  *result_1;
	file  transf_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TRANSFER, TRANSFER_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	// open the file for writing
	
	transf_1_arg.fname = filename;
	transf_1_arg.fcontent = filecontent;
	result_1 = transf_1(&transf_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Result:%d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	transfer_1 (host,argv[2], argv[3]);
exit (0);
}
