/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "transfer.h"
#include <stdio.h>

int *
transf_1_svc(file *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	
    	FILE *fp = fopen(argp->fname, "r");
	if (fp == NULL)
	{
		printf("Error: could not open file %s", argp->fname);
		return 1;
	}
    	
    	// write to the text file
    	for (int i = 0; i < 10; i++)
        	fprintf(fp, argp->fcontent, i + 1);

	// reading line by line, max 256 bytes
    	const unsigned MAX_LENGTH = 256;
    	char buffer[MAX_LENGTH];
    	while (fgets(buffer, MAX_LENGTH, fp))
        	sprintf(result,"%s", buffer);
    	// close the file
    	fclose(fp);

	return &result;
}
